#pragma once

#define LOGENGINE_VER_MAJOR 1
#define LOGENGINE_VER_MINOR 03
#define LOGENGINE_VER_PATCH 0

#define LOGENGINE_VERSION (LOGENGINE_VER_MAJOR * 10000 + LOGENGINE_VER_MINOR * 100 + LOGENGINE_VER_PATCH)
